# @package _global_

dataset:
  view_sampler:
    min_distance_between_context_views: 20
    max_distance_between_context_views: 50
    min_distance_to_context_views: 0
    warm_up_steps: 30000
    initial_min_distance_between_context_views: 15
    initial_max_distance_between_context_views: 30
    num_target_views: 4
