# @package _global_

dataset:
  view_sampler:
    num_target_views: 8
    num_context_views: 6
    min_distance_between_context_views: 20
    max_distance_between_context_views: 50
    min_distance_to_context_views: 0
    warm_up_steps: 1000
    initial_min_distance_between_context_views: 15
    initial_max_distance_between_context_views: 30